<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';
require_once __DIR__ . '/autoload.php';
require_once __DIR__ . '/search.php';
require_once __DIR__ . '/exemplo.php';

return ComposerAutoloaderInit0d04860b45b4e6f439342e9115bb0754::getLoader();
